# Generated by Django 3.0.7 on 2020-07-09 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=100)),
                ('instrument', models.CharField(max_length=50)),
                ('start_time', models.CharField(blank=True, max_length=20, null=True)),
                ('end_time', models.CharField(blank=True, max_length=20, null=True)),
                ('slug', models.SlugField()),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.Track')),
            ],
        ),
    ]
