# Generated by Django 3.0.7 on 2020-07-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solos', '0003_auto_20200709_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='solo',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
