# Generated by Django 3.0.7 on 2020-07-09 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
        ('solos', '0004_solo_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solo',
            name='album',
        ),
        migrations.AlterField(
            model_name='solo',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.Track'),
        ),
    ]
